Add database
LipatovKir/java-filmorate pull request #41
Opened 2023-05-25 05:42 UTC by LipatovKir

2023-05-25 20:31 UTC, Frilock requested changes
Добрый день, оставил довольно много комментариев, причем часть из них шаблонна, то есть в коде есть похожие места где я не стал их указывать, пробегитесь и поправьте везде.

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +@Slf4j
Лишняя аннотация

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>  @Slf4j
Лишняя аннотация

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    private long user1ById;
Числовые префиксы и окончания в названии переменных являются плохой практикой.

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public boolean equals(Object o) {
Довольно простые equals и hashCode, достаточно тех, которые в Data

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    private long filmById;
Зачем добавлять ById? Тогда уж как то filmId или как то так

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mappers.java
> +    public static final RowMapper<User> USER_MAPPER = (ResultSet rs, int rowNum) -> new User(rs.getLong("user_id"), rs.getString("email"), rs.getString("name"), rs.getString("login"), rs.getDate("bir
Строки слишком длинные - это варнинг, сделайте правильные переносы в соответствии с code style. Кроме того, а rs.getDate("birthday") null не вернет?

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public boolean equals(Object o) {
Вроде стандартный equals и hashCode есть в Data

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            Film film1 = new Film(film.getId(), film.getName(), film.getDescription(), film.getReleaseDate(), film.getDuration(), mpaStorage.findMpaById(film.getMpa().getId()).get());
Слишком длинная строка, варнинг будет

А вообще установите себе плагин sonarlint - статический анализатор кода, подскажет ряд хороших практик

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            Film film1 = appointGenre(film);
Числовые окончания это плохая практика, замените

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            Film film = filmStorage.findFilmById(id).get();
Плохая идея, у вас в двух строчках - if (filmStorage.existsById(id)) {
            Film film = filmStorage.findFilmById(id).get();
            
            В первой строчке по сути тоже идет поиск данных, и если их нет то бросается ошибка. 
            Во первых, можно инвертировать условие и избежать лишней вложенности.
            Во вторых, проще - Film film = filmStorage.findFilmById(id), а затем смотрите если пусто то ошибка, если не пусто то get. Получиться 1 запрос вместо двух.
            
            Проверьте код в других аналогичных местах

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    film1.getGenres().add(genreStorage.findGenreById(genre.getId()).get());
Строчку можно вынести за if, если она все равно всегда выполняется. Тогда блок else не будет нужен

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        if (genreStorage.findGenreById(id).isPresent()) {
Инвертируйте условие - избавитесь от лишней вложенности

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          if (user.getName() == null || user.getName().isBlank()) {
Данную проверку можно заменить на StringUtils.isBlank от apache common 3

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user = new User(null, user.getEmail(), user.getName(), user.getLogin(), user.getBirthday());
А почему null передается в id? это как то странно

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    @Override
Закомментированного кода не должно быть в проекте

2023-05-25 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    final String selectFromFilms = "SELECT * FROM FILMS";
Добавьте приватный модификатор (так же можно добавить статический модификатор), тогда поля нужно переименовать на INSERT_INTO..... логику поняли

2023-05-26 04:40 UTC, LipatovKir commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +@Slf4j
Исправлено

2023-05-27 19:04 UTC, closed without merging